language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1

install:
    - composer install

before_script:
    - composer dumpautoload

script:
    - vendor/bin/phpunit
