language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6

install:
    - composer install

before_script:
    - composer run build:expression-parser
    - composer dumpautoload

script:
    - vendor/bin/phpunit
