services:
    combyna.renderer.array:
        class: Combyna\Component\Renderer\Html\ArrayRenderer
        autowire: true

    combyna.renderer.html:
        class: Combyna\Component\Renderer\Html\HtmlRenderer
        autowire: true

    combyna.renderer.html.widget:
        class: Combyna\Component\Renderer\Html\WidgetRenderer\DelegatingWidgetRenderer
        autowire: true
