services:
    combyna.renderer.array:
        class: Combyna\Component\Renderer\Html\ArrayRenderer
        autowire: true

    combyna.renderer.html:
        class: Combyna\Component\Renderer\Html\HtmlRenderer
        autowire: true

    combyna.renderer.trigger:
        class: Combyna\Component\Renderer\Html\TriggerRenderer
        autowire: true

    combyna.renderer.html.ui:
        class: Combyna\Component\Renderer\Html\UiRenderer
        autowire: true

    combyna.renderer.html.widget:
        class: Combyna\Component\Renderer\Html\WidgetRenderer\DelegatingWidgetRenderer
        autowire: true
