services:
    combyna.expression.factory:
        class: Combyna\Component\Expression\ExpressionFactory
        autowire: true
        # Ensure autowiring picks the ExpressionFactory when typehinting for this interface,
        # rather than its sub-interfaces/classes like UiExpressionFactory
        autowiring_types: Combyna\Component\Expression\ExpressionFactoryInterface

    combyna.expression.static_factory:
        class: Combyna\Component\Expression\StaticExpressionFactory
        autowire: true
