services:
    combyna.type.validation.resolved_type_constraint_validator:
        class: Combyna\Component\Type\Validation\Constraint\ResolvedTypeConstraintValidator
        autowire: true
        tags:
            - {name: combyna.validation_constraint_validator}
