services:
    _defaults:
        autowire: true
        autoconfigure: true

    Combyna\Component\Config\YamlParser: ~

    Symfony\Component\Yaml\Parser: ~

    combyna.config.yaml_parser: '@Combyna\Component\Config\YamlParser'
